- name: Task -1 Install Java using Ansible
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - openjdk-11-jdk
  when: group_names == ['test']

- name: install mysql-server
  apt: name=mysql-server state=present
  become: yes
  when: group_names == ['prod']

