---
- hosts: slave1
  tasks:
    - name: Task - 1 Update APT package manager repositories cache
      become: true
      apt:
        update_cache: yes
    - name: Task -2 Install Java using Ansible
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
           - openjdk-11-jdk
- hosts: slave2
  tasks:
   - name: install mysql-server
     apt: name=mysql-server state=present
     become: yes
